### ISSUE TITLE
Python <-- JSON-RPC --> hafas-client

### ISSUE THREAD

**Issue by derhuerst** [benjaminsoellner/quietpaper#2]
Just wanted you to know that there's a [JSON-RPC](https://www.jsonrpc.org/specification) over `stdin`/`stdout` wrapper for `hafas-client`: [`hafas-client-rpc`](https://www.npmjs.com/package/hafas-client-rpc).

See also https://github.com/kennell/schiene/issues/1#issuecomment-445468008.

**Comment by benjaminsoellner** [comment]
Awesome! I didn't come across this when looking for it. Might change it in the future.

**Comment by benjaminsoellner** [comment]
Finally got around addressing this. With https://github.com/benjaminsoellner/quietpaper/commit/6c97fd7327c6509ad7b7f962f20b1f75253960d9
I am switching to a python-only solution (`pyhafas` package) which makes the added complexity of dealing with a NodeJS server unnecessary. Thanks anyway for commenting!
